### ISSUE TITLE
后端技术选型

### ISSUE THREAD

**Issue by tianxuzhang** [VisualCrew/d3js.org.cn#3]
调查Java，Python，Node的优缺点和相关的建站技术。
2015/11/9前给出详细调查结论以及大致的方案。

**Comment by Shauro** [comment]
作为一个Front End Developer, 对Web Back End涉猎并不深，只用过Node.js和Django写server，在这里粗略地谈一下我对这两项技术的理解。Node.js和Django在后端建站上一直是不分上下，各有利弊，具体应该用哪个我觉得还是要看网站的需求。Node.js最显著的优点在于它的异步执行更改了链接到服务器的方式，能处理多个并发连接，适合于在响应客户端之前预计到可能有很高的流量，但需要的服务器逻辑和处理不一定很多的情况，比如Twitter使用node.js快速收集每秒到达的数千条tweets，将它们写入一个排队机制，然后用另一个单独的进程将它们慢慢写入数据库，解决了调用数据库造成阻塞从而引发延迟的问题，大量降低了所需服务器的数量。所以我的建议是先确定网站的功能、预计流量、连接数据库等问题，再决定合适的调用机制，以及开发者的熟练程度，再决定具体的后端语言。

**Comment by ubear** [comment]
一直觉得Java的Web框架过于臃肿，不是很适合咱们这种需求。我认为最好的选择是Python+Django或者Python+Tornado，如果有基于Ruby On Rails的也可以。

Node.js其实从某种角度而言或许有其特殊的可用性。毕竟D3.js是用js写的。前后端一致性也能做出特色。

**Comment by tianxuzhang** [comment]
好的，那就用Node.js
